tables:
- silver_layer.t1_aus_audit_event_hubops
- silver_layer.t1_bgs_bag_hubops
- silver_layer.t1_drs_orderdeliveryevents_final_fulfill_6M
- silver_layer.t1_drs_payload_final_fulfill_6M
- silver_layer.t1_ewbs_ewaybill_data_hubops
- silver_layer.t1_prs_premise_master_hubops
- silver_layer.t1_ss_address_details_hubops
- silver_layer.t1_ss_shipment_operation_code_master
- silver_layer.t1_st_shipment_tat_details_hubops
- silver_layer.t2_hub_outscan_wise_awb_level_details
- silver_layer.t2_master_delivery_events
- silver_layer.t2_master_hubops
- silver_layer.t2_master_hubops_bk
- silver_layer.t3_Eway_Report
- silver_layer.t3_Fastrack_orders_report
- silver_layer.t3_HUB_Audit_Entry_Report_dataset
- silver_layer.t3_booking_data_vs_status_report
- silver_layer.t3_booking_vs_delivery_report
- silver_layer.t3_booking_vs_first_inscan_report
- silver_layer.t3_delivery_mis_report
- silver_layer.t3_incoming_shipments
- silver_layer.t3_inscan_bags_report
- silver_layer.t3_inscan_shipments_report
- silver_layer.t3_master_booking_hubops_delivery
- silver_layer.t3_master_booking_hubops_delivery_pre_clean
- silver_layer.t3_outscan_shipments
- silver_layer.t3_pincode_distance_matrix
- silver_layer.t3_rpt_delivery_channel_analysis
- silver_layer.t3_shipment_current_location
- silver_layer.t3_shipments_inscan_vs_outscan_report
